repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.287
  hooks:
    - id: ruff
      files: ^app/
      args: [
        --fix,
        --exit-non-zero-on-fix
      ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.5.1'
    hooks:
    -   id: mypy
        files: ^app/
        args: [
          --strict,
          --ignore-missing-imports,
          --no-warn-unused-ignores,
          --config-file=pyproject.toml
        ]
        additional_dependencies: [
          pydantic,
          types-cachetools
        ]
-   repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
