[tool.poetry]
name = "fictadvisor-bot"
version = "0.1.0"
description = ""
authors = []
license = "MIT"
readme = "README.md"
packages = [{include = "fictadvisor_bot"}]

[tool.poetry.dependencies]
python = "^3.9"
aiogram = {version = "^3.0.0b7", allow-prereleases = true}
fastapi = "^0.95.0"
pydantic = "^1.10.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
