name: Deployment

on:
  push:
    branches:
      - 'dev'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push app Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: fictadvisor/fictadvisor-bot:${{ github.ref_name }}
          cache-from: type=gha,scope=${{ github.ref_name }}-image
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-image
